bno055:
  ros__parameters:
    connection_type: "uart"
    port: "/dev/ttyUSB0"
    baudrate: 115200
    frequency: 100
    frame_id: "bno055"
    operation_mode: 0x0C
    acc_offset: [0xFFEC, 0x00A5, 0xFFE8]
    mag_offset: [0xFFB4, 0xFE9E, 0x027D]
    gyr_offset: [0x0002, 0xFFFF, 0xFFFF]
